/*Malika Sharma
 *Making a Pizza Frame 
 *25/09/2019
 *
 */

/**
 *
 * @author VIASVS
 */
public class makingapizza extends javax.swing.JFrame {

    /**
     * Creates new form makingapizza
     */
    public makingapizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        makingapizza = new javax.swing.JPanel();
        Tittle = new javax.swing.JLabel();
        diameter = new javax.swing.JLabel();
        textDiameter = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        labelDisplay = new javax.swing.JLabel();
        subtotal = new javax.swing.JLabel();
        taxes = new javax.swing.JLabel();
        grandtotal = new javax.swing.JLabel();
        labelDisplay1 = new javax.swing.JLabel();
        labelDisplay2 = new javax.swing.JLabel();
        labelDisplay3 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        wordDisplay = new javax.swing.JLabel();
        wordDisplay1 = new javax.swing.JLabel();
        wordDisplay2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        makingapizza.setBackground(new java.awt.Color(255, 51, 51));

        Tittle.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tittle.setText("Putrid Pizza");

        diameter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        diameter.setText("Enter Diameter of Pizza (cm)");

        textDiameter.setText("0");
        textDiameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDiameterActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelDisplay.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        subtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtotal.setText("SUBTOTAL ($)");

        taxes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taxes.setText("TAXES ");

        grandtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grandtotal.setText("GRAND TOTAL");

        labelDisplay1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        labelDisplay1.setText("$0.00");

        labelDisplay2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        labelDisplay2.setText("$0.00");

        labelDisplay3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        labelDisplay3.setText("$0.00");

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza (1).png"))); // NOI18N
        image.setText("jLabel1");

        wordDisplay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        wordDisplay1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        wordDisplay2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout makingapizzaLayout = new javax.swing.GroupLayout(makingapizza);
        makingapizza.setLayout(makingapizzaLayout);
        makingapizzaLayout.setHorizontalGroup(
            makingapizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, makingapizzaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDisplay)
                .addGap(85, 85, 85))
            .addGroup(makingapizzaLayout.createSequentialGroup()
                .addGroup(makingapizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(makingapizzaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(makingapizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(makingapizzaLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(makingapizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(makingapizzaLayout.createSequentialGroup()
                                        .addComponent(taxes)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelDisplay2))
                                    .addGroup(makingapizzaLayout.createSequentialGroup()
                                        .addComponent(subtotal)
                                        .addGap(28, 28, 28)
                                        .addComponent(labelDisplay1))))
                            .addComponent(diameter)))
                    .addGroup(makingapizzaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(grandtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDisplay3)))
                .addGroup(makingapizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, makingapizzaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(makingapizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(wordDisplay1)
                            .addComponent(wordDisplay)
                            .addComponent(wordDisplay2))
                        .addGap(106, 106, 106))
                    .addGroup(makingapizzaLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(textDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)
                        .addContainerGap(166, Short.MAX_VALUE))))
            .addGroup(makingapizzaLayout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Tittle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        makingapizzaLayout.setVerticalGroup(
            makingapizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makingapizzaLayout.createSequentialGroup()
                .addGroup(makingapizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(makingapizzaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(makingapizzaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Tittle)))
                .addGap(40, 40, 40)
                .addGroup(makingapizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diameter)
                    .addComponent(textDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(makingapizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotal)
                    .addComponent(labelDisplay1))
                .addGroup(makingapizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(makingapizzaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(makingapizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxes)
                            .addComponent(labelDisplay2))
                        .addGap(31, 31, 31)
                        .addGroup(makingapizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grandtotal)
                            .addComponent(labelDisplay3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, makingapizzaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wordDisplay)
                        .addGap(27, 27, 27)
                        .addComponent(wordDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addComponent(wordDisplay2)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(makingapizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(makingapizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double diameter = Double.parseDouble(textDiameter.getText());
        double subtotal = diameter + 0.75 + 0.99 + diameter * 0.50;
        double taxes = subtotal * 0.13;
        double grandtotal = subtotal + taxes;
        taxes = taxes * 100;
        taxes = Math.round(taxes);
        taxes = taxes / 100;
        subtotal = subtotal * 100;
        subtotal = Math.round(subtotal);
        subtotal = subtotal / 100;
        grandtotal = grandtotal * 100;
        grandtotal = Math.round(grandtotal);
        grandtotal= grandtotal / 100;
        labelDisplay1.setText("$" + taxes);
        labelDisplay2.setText("$" + subtotal);
        labelDisplay3.setText("$" + grandtotal);
        if (diameter <=15)
        wordDisplay.setText("We are going to make you a cute little pizza!");
        if (diameter >=20 && diameter <=40)
        wordDisplay1.setText("This will be delicious!");
        if (diameter >40)
        wordDisplay2.setText("Whoa, big pizza! You might need a truck to get this home!"); 
        {

        }

        {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textDiameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDiameterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDiameterActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(makingapizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(makingapizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(makingapizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(makingapizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new makingapizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tittle;
    private javax.swing.JLabel diameter;
    private javax.swing.JLabel grandtotal;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelDisplay;
    private javax.swing.JLabel labelDisplay1;
    private javax.swing.JLabel labelDisplay2;
    private javax.swing.JLabel labelDisplay3;
    private javax.swing.JPanel makingapizza;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel taxes;
    private javax.swing.JTextField textDiameter;
    private javax.swing.JLabel wordDisplay;
    private javax.swing.JLabel wordDisplay1;
    private javax.swing.JLabel wordDisplay2;
    // End of variables declaration//GEN-END:variables
}
